import { Generator } from "./base/Generator";

/**
 * PackageJsonGenerator: Creates package.json with project metadata and dependencies.
 */
export class PackageJsonGenerator extends Generator {
  // Generates the package.json file
  async generate(): Promise<void> {
    const packageJson = {
      ...this.buildMetadata(),
      ...(this.blueprint.isESM ? { type: "module" } : {}),

      scripts: this.buildScripts(),
      dependencies: this.buildDependencies(),
      devDependencies: this.buildDevDependencies(),
    };
    await this.writeJSON("package.json", packageJson);
  }
  // Section builders
  private buildMetadata(): Record<string, any> {
    return {
      name: this.blueprint.projectName,
      version: "1.0.0",
      description: "An Express.js API server generated by quick-serve-cli",
      main: this.blueprint.isTypescript ? "dist/server.js" : "src/server.js",
      author: "",
      license: "MIT",
      keywords: [
        "express",
        "api",
        "server",
        this.blueprint.language,
        "backend",
        "nodejs",
      ],
    };
  }
  private buildDependencies(): Record<string, any> {
    const deps: Record<string, any> = {
      express: "^5.2.1",
      dotenv: "^17.2.3",
    };
    if (this.blueprint.hasDatabase) {
      switch (this.blueprint.database) {
        case "postgres":
          deps.pg = "^8.18.0";
          break;
        case "mysql":
          deps.mysql2 = "^3.16.2";
          break;
        case "sqlite":
          deps["better-sqlite3"] = "^12.6.2";
          break;
        case "mongo":
          break;
      }
    }
    if (this.blueprint.hasORM) {
      switch (this.blueprint.orm) {
        case "prisma":
          deps["@prisma/client"] = "^7.3.0";
          break;
        case "drizzle":
          deps["drizzle-orm"] = "^0.45.1";
          break;
        case "mongoose":
          deps.mongoose = "^9.1.5";
          break;
      }
    }
    return deps;
  }
  private buildDevDependencies(): Record<string, any> {
    const devDeps: Record<string, any> = {
      nodemon: "^3.1.11",
    };
    if (this.blueprint.isTypescript) {
      devDeps.typescript = "^5.9.3";
      devDeps["@types/node"] = "^25.1.0";
      devDeps["@types/express"] = "^5.0.6";
      devDeps["ts-node"] = "^10.9.2";
      devDeps["tsx"] = "^4.21.0";
    }
    if (this.blueprint.database === "postgres") {
      devDeps["@types/pg"] = "^8.16.0";
    } else if (this.blueprint.database === "mysql") {
      devDeps["@types/mysql"] = "^2.15.27";
    }
    if (this.blueprint.hasORM) {
      switch (this.blueprint.orm) {
        case "prisma":
          devDeps.prisma = "^7.3.0";
          break;
        case "drizzle":
          devDeps["drizzle-kit"] = "^0.31.8";
          break;
      }
    }
    return devDeps;
  }
  private buildScripts(): Record<string, any> {
    const scripts: Record<string, any> = {};
    if (this.blueprint.isTypescript) {
      scripts.dev = "nodemon";
      scripts.build = "tsc";
      scripts.start = "node dist/server.js";
    } else {
      scripts.dev = "nodemon src/server.js";
      scripts.start = "node src/server.js";
    }
    if (this.blueprint.orm === "prisma") {
      scripts["prisma:generate"] = "prisma generate";
      scripts["prisma:migrate"] = "prisma migrate dev";
      scripts["prisma:studio"] = "prisma studio";
      scripts["prisma:push"] = "prisma db push";
    } else if (this.blueprint.orm === "drizzle") {
      scripts["db:generate"] = "drizzle-kit generate:pg";
      scripts["prisma:studio"] = "drizzle-kit studio";
      scripts["prisma:push"] = "drizzle-kit push:pg";
    }
    return scripts;
  }
}
